# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('type', models.CharField(choices=[('register', '用户注册'), ('findpwd', '找回密码')], max_length=12, verbose_name='验证码类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司')),
                ('desc', models.CharField(max_length=200, verbose_name='简介')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('follow', models.IntegerField(verbose_name='关注')),
                ('click', models.IntegerField(verbose_name='点击')),
                ('comment', models.CharField(max_length=300, verbose_name='内容')),
                ('share', models.IntegerField(verbose_name='分享')),
                ('content', models.CharField(max_length=8000, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('url', models.URLField(max_length=100, verbose_name='网址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, verbose_name='中文名称')),
                ('e_name', models.CharField(max_length=50, verbose_name='英文名称')),
                ('url', models.URLField(max_length=100, verbose_name='网址')),
                ('creation_time', models.DateTimeField(verbose_name='注册时间')),
                ('core', models.CharField(max_length=20, verbose_name='机构总部')),
                ('desc', models.CharField(max_length=255, verbose_name='简介')),
                ('accept', models.CharField(max_length=20, verbose_name='受资方')),
                ('invest', models.CharField(max_length=20, verbose_name='投资方')),
                ('category', models.CharField(max_length=20, verbose_name='所属行业')),
                ('invest_time', models.DateTimeField(verbose_name='投资时间')),
                ('content', models.CharField(max_length=8000, verbose_name='结构介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '机构列表',
                'verbose_name_plural': '机构列表',
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('mobile', models.IntegerField(verbose_name='电话')),
                ('postion', models.CharField(max_length=10, verbose_name='职位')),
                ('avatar', models.ImageField(upload_to='image/project-avatar/%Y/%m', verbose_name='头像')),
                ('product_name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('weibo', models.CharField(blank=True, max_length=50, null=True, verbose_name='微博')),
                ('url', models.URLField(max_length=100, verbose_name='网址')),
                ('category', models.CharField(max_length=10, verbose_name='分类')),
                ('addr', models.CharField(max_length=100, verbose_name='地址')),
                ('run_time', models.DateTimeField(verbose_name='产品上线时间')),
                ('logo', models.ImageField(upload_to='image/project-logo/%Y/%m')),
                ('desc', models.CharField(max_length=45, verbose_name='简介')),
                ('content', models.CharField(max_length=300, verbose_name='介绍')),
                ('tag', models.CharField(max_length=30, verbose_name='标签')),
                ('image', models.ImageField(upload_to='image/project-image/%Y/%m')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品发布',
                'verbose_name_plural': '产品发布',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(upload_to='image/user-avatar/%Y/%m', verbose_name='头像')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('is_active', models.CharField(blank=True, choices=[('Y', '激活'), ('N', '未激活')], max_length=2, null=True, verbose_name='激活状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='he.UserInfo', to_field='username', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='content',
            name='categroy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='he.Categroy', to_field='name', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='he.UserInfo', to_field='username', verbose_name='用户名'),
        ),
    ]
