# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0004_auto_20171201_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
