# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0005_auto_20171201_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='add_time',
        ),
    ]
