# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0008_auto_20171205_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='img',
            field=models.ImageField(default=1, upload_to='image/mechanism/%Y/%m', verbose_name='机构图片'),
            preserve_default=False,
        ),
    ]
