# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0009_mechanism_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='look_num',
            field=models.IntegerField(default=0, max_length=10, verbose_name='浏览量'),
        ),
    ]
