# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0011_auto_20171205_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='content',
            field=models.TextField(max_length=8000, verbose_name='结构投资介绍'),
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='desc',
            field=models.TextField(max_length=500, verbose_name='简介'),
        ),
    ]
