# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0013_auto_20171206_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': '咨询文章', 'verbose_name_plural': '咨询文章'},
        ),
    ]
