# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0014_auto_20171206_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_name',
            field=models.CharField(default=1, max_length=20, verbose_name='别名'),
            preserve_default=False,
        ),
    ]
