# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0015_category_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='state',
            field=models.CharField(choices=[('yy', '正在运营'), ('ty', '暂停运营')], max_length=5, verbose_name='运营状态'),
        ),
    ]
