# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0016_auto_20171207_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='state',
            field=models.CharField(choices=[('正在运营', '正在运营'), ('暂停运营', '暂停运营')], max_length=7, verbose_name='运营状态'),
        ),
    ]
