# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0017_auto_20171207_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nid',
            field=models.IntegerField(default=1, verbose_name='所属文章ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='he.City', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='images',
            field=models.ImageField(default='', upload_to='image/consultation/%Y/%m', verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='public',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
        migrations.AddField(
            model_name='public',
            name='follow',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AddField(
            model_name='server',
            name='follow',
            field=models.IntegerField(default=0, verbose_name='关注数量'),
        ),
    ]
