# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0019_auto_20171217_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='city',
        ),
    ]
