# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0021_auto_20171217_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='he.City', verbose_name='城市'),
            preserve_default=False,
        ),
    ]
