# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0022_consultation_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='city',
            new_name='city_id',
        ),
    ]
