# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0023_auto_20171217_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='city_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='he.City', verbose_name='城市'),
        ),
    ]
