# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0025_auto_20171217_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consul',
            name='images',
            field=models.ImageField(upload_to='image/consul/%Y/%m', verbose_name='产品图片'),
        ),
    ]
