# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0028_auto_20171217_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='he.City', verbose_name='城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='click_num',
            field=models.IntegerField(default=1, verbose_name='点击数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='images',
            field=models.ImageField(default=1, upload_to='image/consultation/%Y/%m', verbose_name='产品图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_banner',
            field=models.BooleanField(choices=[(True, '展示'), (False, '不展示')], default=False, verbose_name='是否置顶'),
        ),
    ]
