# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0032_remove_comment_nid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='add_time',
        ),
    ]
