# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0035_auto_20171217_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='he.Consultation', verbose_name='文章ID'),
        ),
    ]
