# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('he', '0036_auto_20171217_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='he.Consultation', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='public',
            name='click_num',
            field=models.IntegerField(verbose_name='点击数量'),
        ),
        migrations.AlterField(
            model_name='public',
            name='follow',
            field=models.IntegerField(verbose_name='关注数量'),
        ),
    ]
